### ISSUE TITLE
Unable to Generate Pictures / Images 

### ISSUE THREAD

**Issue by AlexanderInUM** [hku/aigc-webui#2]
There is no instructions about generating the images and I tried to follow the commands mentioned in README file but only to find that the images cannot be generated.
The screenshots below are the comparison.
![image](https://user-images.githubusercontent.com/113099460/232263784-b09cf968-c1cf-4b7e-9c67-743ee8baeb92.png)

![image](https://user-images.githubusercontent.com/113099460/232263814-568159a1-e631-4a2e-b099-6a561c4e47ce.png)

Besides, I'm sure my API key of Replicate is usable and valid.

**Comment by hku** [comment]
> There is no instructions about generating the images and I tried to follow the commands mentioned in README file but only to find that the images cannot be generated. The screenshots below are the comparison. ![image](https://user-images.githubusercontent.com/113099460/232263784-b09cf968-c1cf-4b7e-9c67-743ee8baeb92.png)
> 
> ![image](https://user-images.githubusercontent.com/113099460/232263814-568159a1-e631-4a2e-b099-6a561c4e47ce.png)
> 
> Besides, I'm sure my API key of Replicate is usable and valid.

you need to switch to another model named `gpt-3.5-enhanced`

**Comment by AlexanderInUM** [comment]
Can free users use that model?

**Comment by hku** [comment]
> Can free users use that model?

all models come with this project are free, but you need an openAI key to use `gpt-3.5-enhanced` or `gpt-turbo`

**Comment by AlexanderInUM** [comment]
> > Can free users use that model?
> 
> all models come with this project are free, but you need an openAI key to use `gpt-3.5-enhanced` or `gpt-turbo`

OK! Thanks!
